name: Docker Build Periodical CI

on:
  schedule:
    - cron: 0 0 * * 1 ## at 00:00 on Monday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: get latest terraform version
      run: echo "::set-env name=tf_version::$( curl -sL https://releases.hashicorp.com/terraform/index.json | jq -r '.versions[].builds[].url' | awk -F \/ '{print $5}' | egrep -v "rc|alpha|beta|oci" | sort | uniq | sort -t. -k 1,1n -k 2,2n -k 3,3n | tail -1)"
    - name: Build the Docker image
      run: docker build --build-arg TF_VER=${tf_version} -t stkhr/terraform-awscli:${tf_version} .
    - name: Push to Docker Hub
      env:
        USER: ${{ secrets.DOCKER_USER }}
        PASS: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u ${USER} -p ${PASS}
        docker push stkhr/terraform-awscli:${tf_version}
    - name: Slack Notification
      if: always()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_CHANNEL: "#develop"
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: terraform version ${tf_version}
        SLACK_TITLE: Update terraform awscli container
        SLACK_USERNAME: monitor
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
